services:
  backend:
    build:
      context: .
    container_name: backend
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
    environment:
      DB_SERVER: db
      DB_NAME: cultural_heritage
      CACHE_SERVER: redis
      IS_PRODUCTION: "true"
    ports:
      - "3001:3000"
    networks:
      - app-network

  db:
    container_name: mongo_db # Set the container name for MongoDB
    image: mongo:latest # Use the official MongoDB image
    ports:
      - "27017" # Expose MongoDB default port
    volumes:
      - mongo_data:/data/db # Persist MongoDB data
    networks:
      - app-network # Connect to the same backend network as express-app

  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
