services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: load-balancer
    depends_on:
      - express
    environment:
      - NGINX_SERVER_NAME=localhost
      - EXPRESS_HOST_1=express-culture-1
      - EXPRESS_HOST_2=express-culture-2
      - EXPRESS_HOST_3=express-culture-3
      - EXPRESS_HOST_4=express-culture-4
      - EXPRESS_HOST_5=express-culture-5
      - EXPRESS_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 3000:3000
  express:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: express
    # ports:
    #   - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./index.js:/app/index.js
      - .env:/app/.env
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:latest
    container_name: cadt-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:cadt-redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
volumes:
  mongodbdata:
